---
title: "Recommender Systems"
output: html_document
---


### Distance measures

We take the value of the rating (or observed usage frequency) provided by each user for each item and calculate an overall distance between the users based on the ratings.

1) **Manhattan distance** (here for 2 dimensions = rated items):  
$|x1 - x2| + |y1 - y2|$

2) **Euclidian distance** (here for 2 dimensions = rated items):  
$\sqrt{(x_{1} - x_{2})^{2} + (y_{1} - y_{2})^{2}}$

3) Generalization of 1 and 2: **Minkowski Distance Measure** for n dimensions:  
  
$d(x,y) = (\Sigma|x_{k} - y_{k}|^{r})^{\frac{1}{r}}$
where x and y are two users, and k is the index of the item both have rated 
  
4) If grade-inflation is present (different users use different scales), use **Pearson correlation** as distance metric for each pair of users: cor(x,y)  
  
5) If the user-item matrix is very sparse, the above metrics will not work correctly, as they are sensitive to zero-matches. Instead, use **cosine distance**:
  
$cos(x,y) = \frac{x \cdot y}{||x|| \times ||y||}$

where · indicates the dot product $\Sigma x_{i}y_{i}$  
and ||x|| indicates the length of the vector x. The length of a vector is $\sqrt{\Sigma x_{i}^{2}}$ 
  
### Collaborative filtering

1) K-nearest neighbors:
    + Compute distance between all users
    + For target user, select *k* other users that are closest
    + Provide a recommendation for an item based on the weighted average score 
    from the *k* users, weight = similarity to the target user

* * *   
Reference:
<http://www.guidetodatamining.com/> 